runtime: php82
default_expiration: "1d"

###################################################

handlers:

- url: /build
  static_dir: public/build
  secure: always
  redirect_http_response_code: 301

- url: /(.*\.(svg|png|txt|css|js))$
  static_files: public/\1
  upload: public/.*\.(svg|png|txt|css|js)$
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

###################################################

automatic_scaling:
  max_instances: 1
