runtime: php83
default_expiration: "1d"

###################################################

handlers:

- url: /build
  static_dir: public/build

- url: /favicon.ico
  static_files: public/favicon.png
  upload: public/favicon.png

- url: /(.*\.(svg|png|txt|css|js))$
  static_files: public/\1
  upload: public/.*\.(svg|png|txt|css|js)$

- url: /.*
  script: auto

###################################################

automatic_scaling:
  max_instances: 1
